services:
  - type: web
    name: hotel-dynamic-pricing-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && gunicorn app.main:app -c ../gunicorn_conf.py
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: 8000
      - key: WEB_CONCURRENCY
        value: 2
      - key: LOG_LEVEL
        value: info
