export const COUNTRIES = [
  "ABW","AGO","AIA","ALB","AND","ARE","ARG","ARM","ASM","AUS","AUT",
  "AZE","BDI","BEL","BEN","BFA","BGD","BGR","BHR","BHS","BIH","BLR",
  "BOL","BRA","BRB","BWA","CAF","CHE","CHL","CHN","CIV","CMR","CN",
  "COL","COM","CPV","CRI","CUB","CYM","CYP","CZE","DEU","DJI","DMA",
  "DNK","DOM","DZA","ECU","EGY","ESP","EST","ETH","FIN","FJI","FRA",
  "FRO","GAB","GBR","GEO","GGY","GHA","GIB","GLP","GNB","GRC","GTM",
  "GUY","HKG","HND","HRV","HUN","IDN","IMN","IND","IRL","IRN","IRQ",
  "ISL","ISR","ITA","JAM","JEY","JOR","JPN","KAZ","KEN","KHM","KIR",
  "KNA","KOR","KWT","LAO","LBN","LBY","LCA","LIE","LKA","LTU","LUX",
  "LVA","MAC","MAR","MCO","MDG","MDV","MEX","MKD","MLI","MLT","MMR",
  "MNE","MOZ","MRT","MUS","MWI","MYS","MYT","NAM","NCL","NGA","NIC",
  "NLD","NOR","NPL","NZL","OMN","PAK","PAN","PER","PHL","PLW","POL",
  "PRI","PRT","PRY","PYF","QAT","ROU","RUS","RWA","SAU","SDN","SEN",
  "SGP","SLE","SLV","SMR","SRB","STP","SUR","SVK","SVN","SWE","SYC",
  "SYR","TGO","THA","TJK","TMP","TUN","TUR","TWN","TZA","UGA","UKR",
  "UMI","URY","USA","UZB","VEN","VGB","VNM","ZAF","ZMB","ZWE",
];
